const TILE_COUNT = 10;
const TILE_SIZE = 16;

const GAME_CONFIG = {
    TILES_COUNT: TILE_COUNT,
    TILE_SIZE: TILE_SIZE,
    HEIGHT: TILE_SIZE * TILE_COUNT,
    WIDTH: TILE_SIZE * TILE_COUNT,
};

export default GAME_CONFIG;
